version: '3.3'

services:
  nginx:
    image: nginx:latest
    ports:
    - '80:80'
    volumes:
    - ./nginx:/etc/nginx/conf.d
    - ./logs/nginx:/var/log/nginx
    - ./wordpress:/var/www/html
    restart: always
  mysql:
    image: mysql:5.7
    ports:
    - '3306:3306'
    volumes:
    - ./db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    restart: always
  wordpress:
    image: wordpress:php7.3-fpm
    user: "${UID:-1000}:${GID:-1000}"
    ports:
    - '9000:9000'
    volumes:
    - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: homestead
      WORDPRESS_DB_NAME: homestead
      WORDPRESS_DB_PASSWORD: secret
    depends_on:
    - mysql
    restart: always