version: '3.3'

services:
  nginx:
    image: nginx:latest
    ports:
    - '80:80'
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    - ./logs/nginx:/var/log/nginx
    - ./modx:/var/www/html
    restart: always
    depends_on:
    - modx_fpm
  mysql:
    image: mysql:5.7
    ports:
    - '3306:3306'
    volumes:
    - ./db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    restart: always
  modx_fpm:
    user: "${UID:-1000}:${GID:-1000}"
    container_name: "modx_fpm"
    build: ./php-fpm
    ports:
    - '9000:9000'
    volumes:
    - ./modx:/var/www/html:rw
    - ./php-fpm/config/php.ini:/usr/local/etc/php/php.ini:ro
    environment:
      MODX_VERSION: 2.7.0
      MODX_DB_HOST: 'mysql:3306'
      MODX_DB_PASSWORD: secret
      MODX_DB_USER: homestead
      MODX_DB_NAME: homestead
    env_file:
#      - ./mariadb/credentials.env
    - ./php-fpm/paths.env
    - ./php-fpm/modx_install.env
    depends_on:
    - mysql
    restart: always
